### ISSUE TITLE
How to refresh keys?

### ISSUE THREAD

**Issue by tjpatter** [mikenemat/gm-onstar-probe#2]
"Updated with new client IDs and JWT signing key" <-- How did you derive these? Open to chatting offline as well, but really want to understand where these come from and how to refresh them should the need arise. Love this project!

**Comment by mikenemat** [comment]
Hey there. The Client ID and the JWT signing key are extracted from the Android APK. Roughly speaking, the steps I performed:

- Decompile the APK
- Inject Smali code to disable certificate pinning
- Inejct Smali code to dump the JWT signing key to logger during the JWT signing process
- Rebuild the APK and deploy it to a device
- Use Burp Suite to perform SSL man-in-the-middling, to capture API calls + client ID, while monitoring logs to observe the JWT signing key.

You could skip burp suite and tampering with cert pinning and stick to dumping the variables to logger if you do not care about observing the API endpoints. I struggled to find the client ID var in the Smali bytecode, so I found it easier to pull that specific value out of the POST requests to the API. 

Periodically, older Client IDs are blacklisted. Along with the new client IDs in the new app APKs, it seems that the JWT signing key is refreshed as well. Blacklisting older Client IDs also breaks the Android app on any devices which may not support the newer version. It is done very rarely. I've only seen it happen once so far.

Good luck!

**Comment by BrendanGrant** [comment]
Much of this should be automatable to some extent, and the fact you have to do so manually, then multiple people look to your repo to find the new keys doesn't scale well.

Any chance you know of a good write up as to how to do all of what you describe? While I'm alright at decompiling APKs and reading for some of the answers I am looking for, I've no experience on the building side of Android apps, though have done much of what you describe on other platforms.

**Comment by BrendanGrant** [comment]
I misspoke perhaps, I was not aiming for you to automate this, given I use these values too I was planning to do so with such instructions. I'll see about some deep diving into building/modifying android apps.

**Comment by BrendanGrant** [comment]
I've managed to decompile the APK, make a minor change, rebuild, sign & deploy working on my end... and it still works.

Any pointers you could provide would be welcome wrt cert pinning & adding logging. Neither Java, Smali or Android development in general are my forte.

This area smells right:
![image](https://user-images.githubusercontent.com/11591952/53705200-80d1b200-3dd7-11e9-8ec1-322ff1f9b714.png)
however my first attempt at changes (not featured here) didn't do it.

Now to keep looking for more...
