### ISSUE TITLE
Not working again - GM blacklisted client ID and rotated key

### ISSUE THREAD

**Issue by mikenemat** [mikenemat/gm-onstar-probe#3]
GM blacklisted the client ID and rotated keys. Sit tight, I'll extract new ones and update the script tonight or tomorrow.

**Comment by sradner13** [comment]
Keys seem to be have rotated again.  Are you still working on this project, or should I work on extracting keys.

Cheers, Scott

**Comment by mikenemat** [comment]
I sold my GM vehicle so unfortunately I don't have a way to test any more. Good luck!

**Comment by sradner13** [comment]
Took me an embarrassingly long time to get everything setup, but I have
extracted the id and key.  If you want to update these are tested.

def clientSecret():
    return jwk.JWK(**{'k': base64.b64encode("snzcCLjKi1CwHnoGvjpr"),
'kty':'oct'})

def clientId():
    return "OMB_CVY_AND_3L0"

Thanks for all the work in the past.  Still working out great.  Much
appreciated.

**Comment by mikenemat** [comment]
Updated!

**Comment by sradner13** [comment]
New keys from the latest update.

Client ID:OMB_CVY_AND_3P0
Client Secret:OxeOjX9FnVkJQQdSuwvR

**Comment by mikenemat** [comment]
Updated!
